<a href="https://colab.research.google.com/github/RIPavicii01/2025_1_BigData/blob/main/03_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
ssudata = {'단과대학':'인문대학', '학과':'사학과', '전화번호':'0380'}
print(ssudata)
print(ssudata['단과대학'])
print(ssudata['학과'])
print(ssudata['전화번호'])
print(type(ssudata))

{'단과대학': '인문대학', '학과': '사학과', '전화번호': '0380'}
인문대학
사학과
0380
<class 'dict'>

In [ ]:
import json

In [ ]:
jdata = json.dumps(ssudata,ensure_ascii= False)
print(jdata)
print(type(jdata))

{"단과대학": "인문대학", "학과": "사학과", "전화번호": "0380"}
<class 'str'>

In [ ]:
ssudata2 = json.loads(jdata)
print(ssudata2)
print(type(ssudata2))

{'단과대학': '인문대학', '학과': '사학과', '전화번호': '0380'}
<class 'dict'>

In [ ]:
major = [
    {'단과대학': '인문대학', '학과': '사학과', '전화번호': '0380'},
    {'단과대학': '자연과학대학', '학과': '물리학과', '전화번호': '0420'},
    {'단과대학': '경영대학', '학과': '회계학과', '전화번호': '0548'}
]

major

[{'단과대학': '인문대학', '학과': '사학과', '전화번호': '0380'},
 {'단과대학': '자연과학대학', '학과': '물리학과', '전화번호': '0420'},
 {'단과대학': '경영대학', '학과': '회계학과', '전화번호': '0548'}]

In [ ]:
print(type(major))

print(major[1]['단과대학'])
print(major[1]['학과'])
print(major[1]['전화번호'])

<class 'list'>
자연과학대학
물리학과
0420

In [ ]:
jdata = json.dumps(major,ensure_ascii=False)
print(type(jdata))
jdata

<class 'str'>

'[{"단과대학": "인문대학", "학과": "사학과", "전화번호": "0380"}, {"단과대학": "자연과학대학", "학과": "물리학과", "전화번호": "0420"}, {"단과대학": "경영대학", "학과": "회계학과", "전화번호": "0548"}]'

In [ ]:
jdata = json.loads(jdata)
jdata

[{'단과대학': '인문대학', '학과': '사학과', '전화번호': '0380'},
 {'단과대학': '자연과학대학', '학과': '물리학과', '전화번호': '0420'},
 {'단과대학': '경영대학', '학과': '회계학과', '전화번호': '0548'}]

In [ ]:
import pandas as pd
data = pd.DataFrame(jdata)
data

     단과대학    학과  전화번호
0    인문대학   사학과  0380
1  자연과학대학  물리학과  0420
2    경영대학  회계학과  0548

In [ ]:
with open ('대학정보.json','w')as fp:
  json.dump(major,fp)

In [ ]:
with open('/content/drive/MyDrive/Colab Notebooks/4week/전국휴양림표준데이터.json','r')as files:
     temp = json.load(files)
temp

{'fields': [{'id': '휴양림명'},
  {'id': '시도명'},
  {'id': '휴양림구분'},
  {'id': '휴양림면적'},
  {'id': '수용인원수'},
  {'id': '입장료'},
  {'id': '숙박가능여부'},
  {'id': '주요시설명'},
  {'id': '소재지도로명주소'},
  {'id': '관리기관명'},
  {'id': '휴양림전화번호'},
  {'id': '홈페이지주소'},
  {'id': '위도'},
  {'id': '경도'},
  {'id': '데이터기준일자'},
  {'id': '제공기관코드'},
  {'id': '제공기관명'}],
 'records': [{'휴양림명': '광치자연휴양림',
   '시도명': '강원도',
   '휴양림구분': '공유림',
   '휴양림면적': '51',
   '수용인원수': '160',
   '입장료': '3000원',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의집, 휴양관, 숲속카페,무장애나눔길',
   '소재지도로명주소': '강원도 양구군 남면 광치령로 1794번길 265',
   '관리기관명': '강원도 양구군청',
   '휴양림전화번호': '033-482-3115',
   '홈페이지주소': 'http://www.foresttrip.go.kr',
   '위도': '38.14199686',
   '경도': '128.0710755',
   '데이터기준일자': '2022-08-31',
   '제공기관코드': '4320000',
   '제공기관명': '강원도 양구군'},
  {'휴양림명': '삼척활기자연휴양림',
   '시도명': '강원도',
   '휴양림구분': '사유림',
   '휴양림면적': '75625',
   '수용인원수': '175',
   '입장료': '0',
   '숙박가능여부': 'Y',
   '주요시설명': '휴양관(송폭헌)+ 한옥(방우재)+ 한옥(세우재)+숲속의집(구희당)+숲속의집(삼락당)',
   '소재지도로명주소': '강원도 삼척시 미로면 준경길 651-43(지번활기리 403-1)',
   '관리기관명': '삼척동해태백산림조합',
   '휴양림전화번호': '033-574-0032',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030104',
   '위도': '37.38099374',
   '경도': '129.0601226',
   '데이터기준일자': '2023-01-04',
   '제공기관코드': '4240000',
   '제공기관명': '강원도 삼척시'},
  {'휴양림명': '데미샘자연휴양림',
   '시도명': '전라북도',
   '휴양림구분': '공유림',
   '휴양림면적': '200000',
   '수용인원수': '131',
   '입장료': '무료',
   '숙박가능여부': 'Y',
   '주요시설명': '휴양관+숲속의집+숲문화마당+명상의숲 등',
   '소재지도로명주소': '전라북도 진안군 백운면 데미샘 1길 172',
   '관리기관명': '전라북도 산림환경연구소',
   '휴양림전화번호': '063-290-6992',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030074',
   '위도': '35.656988',
   '경도': '127.461036',
   '데이터기준일자': '2023-02-27',
   '제공기관코드': '6450000',
   '제공기관명': '전라북도'},
  {'휴양림명': '강릉임해자연휴양림',
   '시도명': '강원도',
   '휴양림구분': '공유림',
   '휴양림면적': '1160000',
   '수용인원수': '105',
   '입장료': '비수기 평일[(6인실)70000원+(5인실)65000원+(4인실)50000원]+비수기 주말[(6인실)120000원+(5인실)110000원+(4인실)90000원]+성수기[(6인실)140000원+(5인실)130000원+(4인실)100000원]',
   '숙박가능여부': 'Y',
   '주요시설명': '숙박동(하늘동+구름동+바다동+숲속동)+숲속의집',
   '소재지도로명주소': '강원도 강릉시 강동면 율곡로 1715-85',
   '관리기관명': '강릉관광개발공사',
   '휴양림전화번호': '033-644-9483',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030100',
   '위도': '37.71856556',
   '경도': '128.9985453',
   '데이터기준일자': '2023-03-15',
   '제공기관코드': '4200000',
   '제공기관명': '강원도 강릉시'},
  {'휴양림명': '금강자연휴양림',
   '시도명': '충청남도',
   '휴양림구분': '공유림',
   '휴양림면적': '1840000',
   '수용인원수': '226',
   '입장료': '1500',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의 집+휴양관+야영장',
   '소재지도로명주소': '세종특별자치시 금남면 산림박물관길110',
   '관리기관명': '산림자원연구소',
   '휴양림전화번호': '041-635-7400',
   '홈페이지주소': 'keumkang.chungnam.go.kr',
   '위도': '36.43769938',
   '경도': '127.2327429',
   '데이터기준일자': '2023-03-24',
   '제공기관코드': '6440000',
   '제공기관명': '충청남도'},
  {'휴양림명': '보현산자연휴양림',
   '시도명': '경상북도',
   '휴양림구분': '공유림',
   '휴양림면적': '51954',
   '수용인원수': '200',
   '입장료': '무료',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의집+산림문화휴양관+야영데크+세미나실+다목적구장+하늘광장+출렁다리+어린이놀이터+우주광장',
   '소재지도로명주소': '경상북도 영천시 화북면 배나무정길 334',
   '관리기관명': '경상북도 영천시청',
   '휴양림전화번호': '054-336-6618',
   '홈페이지주소': 'https://bhforest.foresttrip.go.kr',
   '위도': '36.14210706',
   '경도': '128.9781098',
   '데이터기준일자': '2023-05-15',
   '제공기관코드': '5100000',
   '제공기관명': '경상북도 영천시'},
  {'휴양림명': '만수산자연휴양림',
   '시도명': '충청남도',
   '휴양림구분': '공유림',
   '휴양림면적': '1300000',
   '수용인원수': '150',
   '입장료': '일반1200+청소년900+군인900+어린이600',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의집',
   '소재지도로명주소': '충청남도 부여군 외산면 휴양로 107',
   '관리기관명': '부여군시설관리공단',
   '휴양림전화번호': '041-832-6561',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030007',
   '위도': '36.33854208',
   '경도': '126.7119325',
   '데이터기준일자': '2023-05-10',
   '제공기관코드': '4570000',
   '제공기관명': '충청남도 부여군'},
  {'휴양림명': '남해편백자연휴양림(남해)',
   '시도명': '경상남도',
   '휴양림구분': '국유림',
   '휴양림면적': '1420000',
   '수용인원수': '900',
   '입장료': '개인 어른1000원+개인 청소년 600원+개인 어린이 300원+단체 어른800원+단체 군인청소년 500원+단체 어린이 200원+다자녀가정 면제+동절기 입장료면제(12월~3월)',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의집+휴양관',
   '소재지도로명주소': '경상남도 남해군 삼동면 금암로 658',
   '관리기관명': '산림청',
   '휴양림전화번호': '055-867-7881',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=0192',
   '위도': '34.75216391',
   '경도': '128.0201321',
   '데이터기준일자': '2023-07-06',
   '제공기관코드': '6480000',
   '제공기관명': '경상남도'},
  {'휴양림명': '지리산자연휴양림(함양)',
   '시도명': '경상남도',
   '휴양림구분': '국유림',
   '휴양림면적': '2267840',
   '수용인원수': '800',
   '입장료': '개인 어른1000원+개인 청소년 600원+개인 어린이 300원+단체 어른800원+단체 군인청소년 500원+단체 어린이 200원+다자녀가정 면제+동절기 입장료면제(12월~3월)',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의집+휴양관',
   '소재지도로명주소': '경상남도 함양군 마천면 음정길 152',
   '관리기관명': '산림청',
   '휴양림전화번호': '055-963-8133',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=0190',
   '위도': '35.34644465',
   '경도': '127.6430043',
   '데이터기준일자': '2023-07-06',
   '제공기관코드': '6480000',
   '제공기관명': '경상남도'},
  {'휴양림명': '원동자연휴양림(양산)',
   '시도명': '경상남도',
   '휴양림구분': '사유림',
   '휴양림면적': '747070',
   '수용인원수': '231',
   '입장료': '무료',
   '숙박가능여부': 'Y',
   '주요시설명': '오토캠핑장',
   '소재지도로명주소': '경상남도 양산시 원동면 늘밭로 64',
   '관리기관명': '개인',
   '휴양림전화번호': '0507-1401-583',
   '홈페이지주소': 'https://wondongforest.modoo.at/',
   '위도': '35.39881801',
   '경도': '128.9348445',
   '데이터기준일자': '2023-07-06',
   '제공기관코드': '6480000',
   '제공기관명': '경상남도'},
  {'휴양림명': '덕원자연휴양림(하동)',
   '시도명': '경상남도',
   '휴양림구분': '사유림',
   '휴양림면적': '1378675',
   '수용인원수': '100',
   '입장료': '무료',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의집+휴양관',
   '소재지도로명주소': '경상남도 하동군 옥종면 옥단로 1443-327',
   '관리기관명': '개인',
   '휴양림전화번호': '055-884-0650',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID04030008',
   '위도': '35.22915471',
   '경도': '127.8552761',
   '데이터기준일자': '2023-07-06',
   '제공기관코드': '6480000',
   '제공기관명': '경상남도'},
  {'휴양림명': '중산자연휴양림(산청)',
   '시도명': '경상남도',
   '휴양림구분': '사유림',
   '휴양림면적': '436668',
   '수용인원수': '66',
   '입장료': '무료',
   '숙박가능여부': 'N',
   '주요시설명': '숲속의집+휴양관',
   '소재지도로명주소': '경상남도 산청군 시천면 지리산대로 496-101',
   '관리기관명': '개인',
   '휴양림전화번호': '055-974-2757',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID04030006',
   '위도': '35.2886177',
   '경도': '127.7507425',
   '데이터기준일자': '2023-07-06',
   '제공기관코드': '6480000',
   '제공기관명': '경상남도'},
  {'휴양림명': '생거진천자연휴양림',
   '시도명': '충청북도',
   '휴양림구분': '공유림',
   '휴양림면적': '2210000',
   '수용인원수': '184',
   '입장료': '무료',
   '숙박가능여부': 'Y',
   '주요시설명': '산림문화휴양관+숲속의집12동+연립동+야영센터+관리사무소+유아숲체험원',
   '소재지도로명주소': '충청북도 진천군 백곡면 명암길 435-135',
   '관리기관명': '충청북도 진천군청 산림축산과',
   '휴양림전화번호': '043-539-3554',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030033',
   '위도': '36.923988',
   '경도': '127.3902017',
   '데이터기준일자': '2023-07-05',
   '제공기관코드': '4450000',
   '제공기관명': '충청북도 진천군'},
  {'휴양림명': '여수봉황산자연휴양림',
   '시도명': '전라남도',
   '휴양림구분': '공유림',
   '휴양림면적': '2290000',
   '수용인원수': '230',
   '입장료': '0',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의집+야영장 등',
   '소재지도로명주소': '전라남도 여수시 돌산읍 대복길160',
   '관리기관명': '전라남도 여수시청',
   '휴양림전화번호': '061-643-9180',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030097',
   '위도': '34.61470237',
   '경도': '127.7617999',
   '데이터기준일자': '2023-07-05',
   '제공기관코드': '4810000',
   '제공기관명': '전라남도 여수시'},
  {'휴양림명': '고대산자연휴양림',
   '시도명': '경기도',
   '휴양림구분': '국유림',
   '휴양림면적': '314000',
   '수용인원수': '189',
   '입장료': '어른 : 개인1000원/단체 800원+청소년·군인 : 개인 800원/단체 600원+어린이 : 개인 500원/단체 300원',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의집 14동14실+산림휴양관 1동2층6실+숲속수련원 1동1실+방문자센터 1동2층 야영장데크 20개소',
   '소재지도로명주소': '경기도 연천군 신서면 고대산길 84-79',
   '관리기관명': '경기도 연천군청 산림녹지과',
   '휴양림전화번호': '031-834-2200',
   '홈페이지주소': 'https://godaesan.foresttrip.go.kr',
   '위도': '38.21125391',
   '경도': '127.1507058',
   '데이터기준일자': '2023-07-03',
   '제공기관코드': '4140000',
   '제공기관명': '경기도 연천군'},
  {'휴양림명': '간월산자연휴양림',
   '시도명': '울산광역시',
   '휴양림구분': '사유림',
   '휴양림면적': '597890',
   '수용인원수': '200',
   '입장료': '주중10~20만원+주말15~30만원',
   '숙박가능여부': 'Y',
   '주요시설명': '관리실+수영장+연수원',
   '소재지도로명주소': '울산광역시 울주군 상북면 작괘로 607-15',
   '관리기관명': '천광디엔씨',
   '휴양림전화번호': '052-263-6644',
   '홈페이지주소': 'https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/CmpngInfo/selectCmpngInfoList.do?mn=NKFS_03_01_01_02_04&restTpcd=01&restMngmeMnbdCd=003',
   '위도': '35.5670959',
   '경도': '129.0560416',
   '데이터기준일자': '2023-06-30',
   '제공기관코드': '3730000',
   '제공기관명': '울산광역시 울주군'},
  {'휴양림명': '용인자연휴양림',
   '시도명': '경기도',
   '휴양림구분': '공유림',
   '휴양림면적': '1801693',
   '수용인원수': '1800',
   '입장료': '개인성인2000원+개인청소년/군인/국가보훈대상자/다자녀가정1000원+개인어린이500원+단체성인1600원+단체청소년/군인/국가보훈대상자/다자녀가정800원+단체어린이400원',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의집+숲속체험관+목조주택+생태습지+야영장+잔디광장+짚라인+목재문화체험관 등',
   '소재지도로명주소': '경기도 용인시 처인구 모현면 초부로 220',
   '관리기관명': '경기도 용인시청',
   '휴양림전화번호': '031-336-0040',
   '홈페이지주소': 'https://yonginforest.foresttrip.go.kr/',
   '위도': '37.314713',
   '경도': '127.265315',
   '데이터기준일자': '2023-06-28',
   '제공기관코드': '4050000',
   '제공기관명': '경기도 용인시'},
  {'휴양림명': '제암산자연휴양림',
   '시도명': '전라남도',
   '휴양림구분': '공유림',
   '휴양림면적': '1600000',
   '수용인원수': '3000',
   '입장료': '개인(일반1000원+단체800원+할인500원)+청소년·군인(일반600원+단체500원+할인300원)+어린이(일반400원+단체300원+할인200원)',
   '숙박가능여부': 'Y',
   '주요시설명': '숙박+야영장+물놀이장+더늠길+숲속교육관+족구장데크+모험시설+하이데크+잔디광장',
   '소재지도로명주소': '전라남도 보성군 웅치면 대산길 330',
   '관리기관명': '전라남도 보성군청',
   '휴양림전화번호': '061-852-4434',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030090',
   '위도': '34.70050454',
   '경도': '126.9855053',
   '데이터기준일자': '2023-06-27',
   '제공기관코드': '4890000',
   '제공기관명': '전라남도 보성군'},
  {'휴양림명': '좌구산자연휴양림',
   '시도명': '충청북도',
   '휴양림구분': '공유림',
   '휴양림면적': '730000',
   '수용인원수': '250',
   '입장료': '없음',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의 집+황토집+별무리하우스+병영하우스+줄타기+썰매장+숲속모험시설+좌구산숲명상의집,+명상구름다리+좌구산천문대 등',
   '소재지도로명주소': '충청북도 증평군 증평읍 솟점말길 107',
   '관리기관명': '충청북도 증평군 휴양공원사업소',
   '휴양림전화번호': '043-835-4551',
   '홈페이지주소': 'https://jpjwagu.foresttrip.go.kr',
   '위도': '36.70556821',
   '경도': '127.6511216',
   '데이터기준일자': '2023-06-27',
   '제공기관코드': '5570000',
   '제공기관명': '충청북도 증평군'},
  {'휴양림명': '옥화자연휴양림',
   '시도명': '충청북도',
   '휴양림구분': '공유림',
   '휴양림면적': '862790',
   '수용인원수': '373',
   '입장료': '어른(개인 1000원+단체 500원)+청소년(개인 500원+단체 300원)+어린이(개인 300원+단체 200원)+군인(개인 500원+단체 300원)+지역주민(개인 500원+단체 300원)',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의집+산림휴양관+국민여가오토캠핑장+물놀이장 등',
   '소재지도로명주소': '충청북도 청주시 상당구 미원면 운암옥화길 140',
   '관리기관명': '청주시 푸른도시사업본부',
   '휴양림전화번호': '043-270-7384',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030054',
   '위도': '36.59895012',
   '경도': '127.6943716',
   '데이터기준일자': '2023-06-26',
   '제공기관코드': '5710000',
   '제공기관명': '충청북도 청주시'},
  {'휴양림명': '동두천자연휴양림',
   '시도명': '경기도',
   '휴양림구분': '공유림',
   '휴양림면적': '700000',
   '수용인원수': '1000',
   '입장료': '성인2000+청소년구인1500+아동1000',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의집+야외데크+치유의숲+유아숲체험원',
   '소재지도로명주소': '경기도 동두천시 탑동가산로 1',
   '관리기관명': '경기도 동두천시청 관광휴양과',
   '휴양림전화번호': '031-860-3256',
   '홈페이지주소': 'https://blog.naver.com/ddcforest',
   '위도': '37.88988548',
   '경도': '127.1371472',
   '데이터기준일자': '2023-06-23',
   '제공기관코드': '3920000',
   '제공기관명': '경기도 동두천시'},
  {'휴양림명': '서귀포자연휴양림',
   '시도명': '제주특별자치도',
   '휴양림구분': '국유림',
   '휴양림면적': '2550000',
   '수용인원수': '1500',
   '입장료': '어른 1000원+청소년 600원+어린이 300원+(단체)어른 800원+(단체)청소년 500원+(단체)어린이 200원',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의집+산림휴양관+세미나실+야영장+생태탐방코스',
   '소재지도로명주소': '제주특별자치도 서귀포시 1100로 882',
   '관리기관명': '제주특별자치도 서귀포시청',
   '휴양림전화번호': '064-738-4544',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030013',
   '위도': '33.3115002',
   '경도': '126.458761',
   '데이터기준일자': '2023-06-13',
   '제공기관코드': '6520000',
   '제공기관명': '제주특별자치도 서귀포시'},
  {'휴양림명': '붉은오름자연휴양림',
   '시도명': '제주특별자치도',
   '휴양림구분': '공유림',
   '휴양림면적': '1900000',
   '수용인원수': '1500',
   '입장료': '어른 1000원+청소년·군인 600원+(단체)어른 800원+(단체)청소년·군인 500원',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의집+산림문화휴양관+세미나실+오름등반로+야외공연장',
   '소재지도로명주소': '제주특별자치도 서귀포시 표선면 남조로 1487-73',
   '관리기관명': '제주특별자치도 서귀포시청',
   '휴양림전화번호': '064-760-3481',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030014',
   '위도': '33.401429',
   '경도': '126.675671',
   '데이터기준일자': '2023-06-13',
   '제공기관코드': '6520000',
   '제공기관명': '제주특별자치도 서귀포시'},
  {'휴양림명': '서귀포 치유의 숲',
   '시도명': '제주특별자치도',
   '휴양림구분': '공유림',
   '휴양림면적': '1740000',
   '수용인원수': '600',
   '입장료': '어른 1000원+청소년 600원+(단체)어른 800원+(단체)청소년 500원',
   '숙박가능여부': 'N',
   '주요시설명': '치유숲길',
   '소재지도로명주소': '제주특별자치도 서귀포시 산록남로 2271',
   '관리기관명': '제주특별자치도 서귀포시청',
   '휴양림전화번호': '064-760-3067',
   '홈페이지주소': 'https://seogwipo.go.kr/healing/index.htm',
   '위도': '33.291941',
   '경도': '126.527902',
   '데이터기준일자': '2023-06-13',
   '제공기관코드': '6520000',
   '제공기관명': '제주특별자치도 서귀포시'},
  {'휴양림명': '칠갑산자연휴양림',
   '시도명': '충청남도',
   '휴양림구분': '공유림',
   '휴양림면적': '73000',
   '수용인원수': '500',
   '입장료': '개인 일반 1000원 +개인 청소년·군인 800원+개인 어린이 500원+단체 일반 800원+단체 청소년·군인 600원+단체 어린이 300원 + 청양 부여 공주 군(시)민 무료',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의 집+산림문화 휴양관+원두막+기타시설 등',
   '소재지도로명주소': '충청남도 청양군 대치면 칠갑산로 668-103',
   '관리기관명': '충청남도 청양군공공시설사업소',
   '휴양림전화번호': '041-940-2429',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030044',
   '위도': '36.431589',
   '경도': '126.8438227',
   '데이터기준일자': '2023-06-22',
   '제공기관코드': '4590000',
   '제공기관명': '충청남도 청양군'},
  {'휴양림명': '치악산자연휴양림',
   '시도명': '강원도',
   '휴양림구분': '공유림',
   '휴양림면적': '1700000',
   '수용인원수': '120',
   '입장료': '일반(개인 2000+청소년 및 군인 1500+어린이 1000)+단체(어른 1500+청소년 및 군인 1000+어린이 700)',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의집+주차장+산책로',
   '소재지도로명주소': '강원도 원주시 판부면 휴양림길 66',
   '관리기관명': '강원도 원주시청 산림과',
   '휴양림전화번호': '033-762-8288',
   '홈페이지주소': 'https://foresttrip.go.kr/indvz/main.do?hmpgId=ID02030024',
   '위도': '37.255878',
   '경도': '128.031372',
   '데이터기준일자': '2023-02-06',
   '제공기관코드': '4190000',
   '제공기관명': '강원도 원주시'},
  {'휴양림명': '숲체원',
   '시도명': '강원도',
   '휴양림구분': '국유림',
   '휴양림면적': '159710',
   '수용인원수': '300',
   '입장료': '별도 입장료 없음',
   '숙박가능여부': 'Y',
   '주요시설명': '탐방로, 숙박동, 강의실',
   '소재지도로명주소': '강원도 횡성군 둔내면 청태산로 777',
   '관리기관명': '산림청',
   '휴양림전화번호': '033-340-6300',
   '홈페이지주소': 'https://hoengseong.fowi.or.kr/',
   '위도': '37.53722046',
   '경도': '128.2866886',
   '데이터기준일자': '2022-06-22',
   '제공기관코드': '4260000',
   '제공기관명': '강원도 횡성군'},
  {'휴양림명': '청태산휴양림',
   '시도명': '강원도',
   '휴양림구분': '국유림',
   '휴양림면적': '159520',
   '수용인원수': '1500',
   '입장료': '일반 : 1000원+청소년 : 600원+어린이 : 300원',
   '숙박가능여부': 'Y',
   '주요시설명': '제1산림문화휴양관, 제2산림문화휴양관, 숲속의집, 숲속수련장(중형, 소형), 대형숲속수영장(회의실), 야영장, 인도네시아 전통 전시관, 숲생태체험실, BIY목공교실',
   '소재지도로명주소': '강원도 횡성군 둔내면 청태산로 610',
   '관리기관명': '산림청',
   '휴양림전화번호': '033-343-9707',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=0106',
   '위도': '37.52907993',
   '경도': '128.2968658',
   '데이터기준일자': '2022-06-22',
   '제공기관코드': '4260000',
   '제공기관명': '강원도 횡성군'},
  {'휴양림명': '민주지산자연휴양림',
   '시도명': '충청북도',
   '휴양림구분': '공유림',
   '휴양림면적': '1800000',
   '수용인원수': '394',
   '입장료': '어른 1000원+청소년 500원+어린이 300원',
   '숙박가능여부': 'N',
   '주요시설명': '버섯동+생화동+국악동+식당+황토방+황토찝질방+학습관+너와집+산림문화휴양관1,2층 세미나실+치유숙소6개소+치유센터+진료동+치유센터치유동+야외 치유시설+야영장+족구장 등',
   '소재지도로명주소': '충청북도 영동군 용화면 휴양림길 60',
   '관리기관명': '충청북도 영동군청 산림과',
   '휴양림전화번호': '043-740-3437',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030107',
   '위도': '36.05313182',
   '경도': '127.8243888',
   '데이터기준일자': '2022-11-30',
   '제공기관코드': '4440000',
   '제공기관명': '충청북도 영동군'},
  {'휴양림명': '태백고원자연휴양림',
   '시도명': '강원도',
   '휴양림구분': '국유림',
   '휴양림면적': '1404000',
   '수용인원수': '110',
   '입장료': '2000원',
   '숙박가능여부': 'Y',
   '주요시설명': '산림문화휴양관, 숲속의 집 , 야영장',
   '소재지도로명주소': '강원도 태백시 머리골길153',
   '관리기관명': '태백시농업기술센터 산림축산과',
   '휴양림전화번호': '033-550-2849',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030022',
   '위도': '37.12357654',
   '경도': '129.0603832',
   '데이터기준일자': '2023-04-05',
   '제공기관코드': '4220000',
   '제공기관명': '강원도 태백시'},
  {'휴양림명': '교래자연휴양림',
   '시도명': '제주특별자치도',
   '휴양림구분': '공유림',
   '휴양림면적': '230',
   '수용인원수': '1500',
   '입장료': '어른1000원+청소년600원+군인600원+단체어른800원+단체청소년500원+단체군인500원',
   '숙박가능여부': 'Y',
   '주요시설명': '휴양림+숙박+공연장등',
   '소재지도로명주소': '제주특별자치도 제주시 조천읍 남조로 2023',
   '관리기관명': '제주특별자치도청',
   '휴양림전화번호': '064-783-7482',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030056',
   '위도': '33.45136376',
   '경도': '126.6567109',
   '데이터기준일자': '2023-07-06',
   '제공기관코드': '6510000',
   '제공기관명': '제주특별자치도 제주시'},
  {'휴양림명': '태학산자연휴양림',
   '시도명': '충청남도',
   '휴양림구분': '공유림',
   '휴양림면적': '1055598',
   '수용인원수': '1000',
   '입장료': '없음',
   '숙박가능여부': 'N',
   '주요시설명': '숲속의집+잔디광장+숲속공연장 등',
   '소재지도로명주소': '충청남도 천안시 동남구 풍세면 휴양림길 127',
   '관리기관명': '충청남도 천안시청',
   '휴양림전화번호': '041-529-5108',
   '홈페이지주소': 'http://www.cfmc.or.kr/_taehaksan/',
   '위도': '36.72734819',
   '경도': '127.0903273',
   '데이터기준일자': '2023-06-30',
   '제공기관코드': '4490000',
   '제공기관명': '충청남도 천안시'},
  {'휴양림명': '비학산자연휴양림',
   '시도명': '경상북도',
   '휴양림구분': '공유림',
   '휴양림면적': '2280000',
   '수용인원수': '150',
   '입장료': '숙박 : 7만원 + 11만원+ 14만원',
   '숙박가능여부': 'Y',
   '주요시설명': '산림휴양관+숲속의 집+테라스하우스+카라반+야외데크+생태숲 등',
   '소재지도로명주소': '경상북도 포항시 북구 기북면 비학산길 302',
   '관리기관명': '경상북도 포항시청',
   '휴양림전화번호': '054-252-3275',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030052',
   '위도': '36.14703337',
   '경도': '129.2111071',
   '데이터기준일자': '2023-07-06',
   '제공기관코드': '5020000',
   '제공기관명': '경상북도 포항시'},
  {'휴양림명': '성불산자연휴양림',
   '시도명': '충청북도',
   '휴양림구분': '공유림',
   '휴양림면적': '58',
   '수용인원수': '242',
   '입장료': '입장료 개인(어린이 1000원+청소년 1500원+군인 1500원+일반 2000원)+입장료 단체(30명 이상)(어린이 500원+청소년 1000원+군인 1000원+일반 1500원)+주차료(경형 1500원+중소형 3000원+대형 5000원+숙박시설 사용자 무료)',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의집A+숲속의집B+산림문화휴양관+숲관광메가시티+생태숲학습관+한옥체험관+생태공원+미선향테마파크무인카페+수석전시관 등',
   '소재지도로명주소': '충청북도 괴산군 괴산읍 충민로기곡길 78',
   '관리기관명': '충청북도 괴산군청 산림녹지과',
   '휴양림전화번호': '043-830-2679',
   '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030070',
   '위도': '36.80804701',
   '경도': '127.8467688',
   '데이터기준일자': '2023-07-10',
   '제공기관코드': '4460000',
   '제공기관명': '충청북도 괴산군'},
  {'휴양림명': '비슬산자연휴양림',
   '시도명': '대구광역시',
   '휴양림구분': '공유림',
   '휴양림면적': '1000000',
   '수용인원수': '285',
   '입장료': '없음',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의집+통나무집+야영장+반딧불이전기차등',
   '소재지도로명주소': '대구광역시 달성군 유가읍 일연선사길 99',
   '관리기관명': '대구광역시 달성군시설관리공단',
   '휴양림전화번호': '053-659-4400',
   '홈페이지주소': 'http://bisulsan.dssiseol.or.kr/bisulsan/html/main.html',
   '위도': '35.69001083',
   '경도': '128.5129017',
   '데이터기준일자': '2023-07-10',
   '제공기관코드': '3480000',
   '제공기관명': '대구광역시 달성군'},
  {'휴양림명': '화원자연휴양림',
   '시도명': '대구광역시',
   '휴양림구분': '공유림',
   '휴양림면적': '720000',
   '수용인원수': '115',
   '입장료': '없음',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의집+산림문화휴양관+산림욕장+전망데크등',
   '소재지도로명주소': '대구광역시 달성군 화원읍 화원휴양림길 126',
   '관리기관명': '대구광역시 달성군시설관리공단',
   '휴양림전화번호': '053-659-4455',
   '홈페이지주소': 'http://hwawon.dssiseol.or.kr/hwawon/html/main.html',
   '위도': '35.77179173',
   '경도': '128.5367385',
   '데이터기준일자': '2023-07-10',
   '제공기관코드': '3480000',
   '제공기관명': '대구광역시 달성군'},
  {'휴양림명': '천보산자연휴양림',
   '시도명': '경기도',
   '휴양림구분': '공유림',
   '휴양림면적': '1165686',
   '수용인원수': '80',
   '입장료': '일반 2000원+단체 1400원',
   '숙박가능여부': 'Y',
   '주요시설명': '숲속의집+휴양관+야영장 등',
   '소재지도로명주소': '경기도 포천시 원동교길 309',
   '관리기관명': '경기도 포천시청',
   '휴양림전화번호': '031-538-3554',
   '홈페이지주소': '',
   '위도': '37.85576406',
   '경도': '127.1190897',
   '데이터기준일자': '2023-07-07',
   '제공기관코드': '5600000',
   '제공기관명': '경기도 포천시'},
  {'휴양림명': '국망봉자연휴양림',
   '시도명': '경기도',
   '휴양림구분': '사유림',
   '휴양림면적': '2554814',
   '수용인원수': '60',
   '입장료': '관람객 5000원+등산객2000원',
   '숙박가능여부': 'Y',
   '주요시설명': '통나무 집+캠핑장 등',
   '소재지도로명주소': '경기도 포천시 이동면 늠바위길 207-28',
   '관리기관명': '김봉일',
   '휴양림전화번호': '031-532-0014',
   '홈페이지주소': 'www.kookmang.co.kr',
   '위도': '38.02891868',
   '경도': '127.3962681',
   '데이터기준일자': '2023-07-07',
   '제공기관코드': '5600000',
   '제공기관명': '경기도 포천시'},
  {'휴양림명': '안면도자연휴양림',
   '시도명': '충청남도',
   '휴양림구분': '국유림',
   '휴양림면적': '1350000',
   '수용인원수': '6000',
   '입장료': '일반 1000원+청소년 800원+군인 800원+어린이 400원',
   '숙박가능여부': 'Y',
   '주요시설명': '전시관+수목원+숲속의집 등',
   '소재지도로명주소': '충청남도 태안군 안면읍 안면대로3195-6',
   '관리기관명': '충청남도 산림환경연구소 휴양림관리사무소',
   '휴양림전화번호': '041-674-5019',
   '홈페이지주소': 'www.anmyonhuyang.go.kr',
   '위도': '36.49670127',
   '경도': '126.3588291',
   '데이터기준일자': '2023-07-05',
   '제공기관코드': '4620000',
   '제공기관명': '충청남도 태안군'},
  {'휴양림명': '변산자연휴양림',
   '시도명': '전라북도',
   '휴양림구분': '국유림',
   '휴양림면적': '311000',

In [ ]:
data = []
for d in temp['records']:
  data.append(d)
data

[{'휴양림명': '광치자연휴양림',
  '시도명': '강원도',
  '휴양림구분': '공유림',
  '휴양림면적': '51',
  '수용인원수': '160',
  '입장료': '3000원',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의집, 휴양관, 숲속카페,무장애나눔길',
  '소재지도로명주소': '강원도 양구군 남면 광치령로 1794번길 265',
  '관리기관명': '강원도 양구군청',
  '휴양림전화번호': '033-482-3115',
  '홈페이지주소': 'http://www.foresttrip.go.kr',
  '위도': '38.14199686',
  '경도': '128.0710755',
  '데이터기준일자': '2022-08-31',
  '제공기관코드': '4320000',
  '제공기관명': '강원도 양구군'},
 {'휴양림명': '삼척활기자연휴양림',
  '시도명': '강원도',
  '휴양림구분': '사유림',
  '휴양림면적': '75625',
  '수용인원수': '175',
  '입장료': '0',
  '숙박가능여부': 'Y',
  '주요시설명': '휴양관(송폭헌)+ 한옥(방우재)+ 한옥(세우재)+숲속의집(구희당)+숲속의집(삼락당)',
  '소재지도로명주소': '강원도 삼척시 미로면 준경길 651-43(지번활기리 403-1)',
  '관리기관명': '삼척동해태백산림조합',
  '휴양림전화번호': '033-574-0032',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030104',
  '위도': '37.38099374',
  '경도': '129.0601226',
  '데이터기준일자': '2023-01-04',
  '제공기관코드': '4240000',
  '제공기관명': '강원도 삼척시'},
 {'휴양림명': '데미샘자연휴양림',
  '시도명': '전라북도',
  '휴양림구분': '공유림',
  '휴양림면적': '200000',
  '수용인원수': '131',
  '입장료': '무료',
  '숙박가능여부': 'Y',
  '주요시설명': '휴양관+숲속의집+숲문화마당+명상의숲 등',
  '소재지도로명주소': '전라북도 진안군 백운면 데미샘 1길 172',
  '관리기관명': '전라북도 산림환경연구소',
  '휴양림전화번호': '063-290-6992',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030074',
  '위도': '35.656988',
  '경도': '127.461036',
  '데이터기준일자': '2023-02-27',
  '제공기관코드': '6450000',
  '제공기관명': '전라북도'},
 {'휴양림명': '강릉임해자연휴양림',
  '시도명': '강원도',
  '휴양림구분': '공유림',
  '휴양림면적': '1160000',
  '수용인원수': '105',
  '입장료': '비수기 평일[(6인실)70000원+(5인실)65000원+(4인실)50000원]+비수기 주말[(6인실)120000원+(5인실)110000원+(4인실)90000원]+성수기[(6인실)140000원+(5인실)130000원+(4인실)100000원]',
  '숙박가능여부': 'Y',
  '주요시설명': '숙박동(하늘동+구름동+바다동+숲속동)+숲속의집',
  '소재지도로명주소': '강원도 강릉시 강동면 율곡로 1715-85',
  '관리기관명': '강릉관광개발공사',
  '휴양림전화번호': '033-644-9483',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030100',
  '위도': '37.71856556',
  '경도': '128.9985453',
  '데이터기준일자': '2023-03-15',
  '제공기관코드': '4200000',
  '제공기관명': '강원도 강릉시'},
 {'휴양림명': '금강자연휴양림',
  '시도명': '충청남도',
  '휴양림구분': '공유림',
  '휴양림면적': '1840000',
  '수용인원수': '226',
  '입장료': '1500',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의 집+휴양관+야영장',
  '소재지도로명주소': '세종특별자치시 금남면 산림박물관길110',
  '관리기관명': '산림자원연구소',
  '휴양림전화번호': '041-635-7400',
  '홈페이지주소': 'keumkang.chungnam.go.kr',
  '위도': '36.43769938',
  '경도': '127.2327429',
  '데이터기준일자': '2023-03-24',
  '제공기관코드': '6440000',
  '제공기관명': '충청남도'},
 {'휴양림명': '보현산자연휴양림',
  '시도명': '경상북도',
  '휴양림구분': '공유림',
  '휴양림면적': '51954',
  '수용인원수': '200',
  '입장료': '무료',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의집+산림문화휴양관+야영데크+세미나실+다목적구장+하늘광장+출렁다리+어린이놀이터+우주광장',
  '소재지도로명주소': '경상북도 영천시 화북면 배나무정길 334',
  '관리기관명': '경상북도 영천시청',
  '휴양림전화번호': '054-336-6618',
  '홈페이지주소': 'https://bhforest.foresttrip.go.kr',
  '위도': '36.14210706',
  '경도': '128.9781098',
  '데이터기준일자': '2023-05-15',
  '제공기관코드': '5100000',
  '제공기관명': '경상북도 영천시'},
 {'휴양림명': '만수산자연휴양림',
  '시도명': '충청남도',
  '휴양림구분': '공유림',
  '휴양림면적': '1300000',
  '수용인원수': '150',
  '입장료': '일반1200+청소년900+군인900+어린이600',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의집',
  '소재지도로명주소': '충청남도 부여군 외산면 휴양로 107',
  '관리기관명': '부여군시설관리공단',
  '휴양림전화번호': '041-832-6561',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030007',
  '위도': '36.33854208',
  '경도': '126.7119325',
  '데이터기준일자': '2023-05-10',
  '제공기관코드': '4570000',
  '제공기관명': '충청남도 부여군'},
 {'휴양림명': '남해편백자연휴양림(남해)',
  '시도명': '경상남도',
  '휴양림구분': '국유림',
  '휴양림면적': '1420000',
  '수용인원수': '900',
  '입장료': '개인 어른1000원+개인 청소년 600원+개인 어린이 300원+단체 어른800원+단체 군인청소년 500원+단체 어린이 200원+다자녀가정 면제+동절기 입장료면제(12월~3월)',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의집+휴양관',
  '소재지도로명주소': '경상남도 남해군 삼동면 금암로 658',
  '관리기관명': '산림청',
  '휴양림전화번호': '055-867-7881',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=0192',
  '위도': '34.75216391',
  '경도': '128.0201321',
  '데이터기준일자': '2023-07-06',
  '제공기관코드': '6480000',
  '제공기관명': '경상남도'},
 {'휴양림명': '지리산자연휴양림(함양)',
  '시도명': '경상남도',
  '휴양림구분': '국유림',
  '휴양림면적': '2267840',
  '수용인원수': '800',
  '입장료': '개인 어른1000원+개인 청소년 600원+개인 어린이 300원+단체 어른800원+단체 군인청소년 500원+단체 어린이 200원+다자녀가정 면제+동절기 입장료면제(12월~3월)',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의집+휴양관',
  '소재지도로명주소': '경상남도 함양군 마천면 음정길 152',
  '관리기관명': '산림청',
  '휴양림전화번호': '055-963-8133',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=0190',
  '위도': '35.34644465',
  '경도': '127.6430043',
  '데이터기준일자': '2023-07-06',
  '제공기관코드': '6480000',
  '제공기관명': '경상남도'},
 {'휴양림명': '원동자연휴양림(양산)',
  '시도명': '경상남도',
  '휴양림구분': '사유림',
  '휴양림면적': '747070',
  '수용인원수': '231',
  '입장료': '무료',
  '숙박가능여부': 'Y',
  '주요시설명': '오토캠핑장',
  '소재지도로명주소': '경상남도 양산시 원동면 늘밭로 64',
  '관리기관명': '개인',
  '휴양림전화번호': '0507-1401-583',
  '홈페이지주소': 'https://wondongforest.modoo.at/',
  '위도': '35.39881801',
  '경도': '128.9348445',
  '데이터기준일자': '2023-07-06',
  '제공기관코드': '6480000',
  '제공기관명': '경상남도'},
 {'휴양림명': '덕원자연휴양림(하동)',
  '시도명': '경상남도',
  '휴양림구분': '사유림',
  '휴양림면적': '1378675',
  '수용인원수': '100',
  '입장료': '무료',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의집+휴양관',
  '소재지도로명주소': '경상남도 하동군 옥종면 옥단로 1443-327',
  '관리기관명': '개인',
  '휴양림전화번호': '055-884-0650',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID04030008',
  '위도': '35.22915471',
  '경도': '127.8552761',
  '데이터기준일자': '2023-07-06',
  '제공기관코드': '6480000',
  '제공기관명': '경상남도'},
 {'휴양림명': '중산자연휴양림(산청)',
  '시도명': '경상남도',
  '휴양림구분': '사유림',
  '휴양림면적': '436668',
  '수용인원수': '66',
  '입장료': '무료',
  '숙박가능여부': 'N',
  '주요시설명': '숲속의집+휴양관',
  '소재지도로명주소': '경상남도 산청군 시천면 지리산대로 496-101',
  '관리기관명': '개인',
  '휴양림전화번호': '055-974-2757',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID04030006',
  '위도': '35.2886177',
  '경도': '127.7507425',
  '데이터기준일자': '2023-07-06',
  '제공기관코드': '6480000',
  '제공기관명': '경상남도'},
 {'휴양림명': '생거진천자연휴양림',
  '시도명': '충청북도',
  '휴양림구분': '공유림',
  '휴양림면적': '2210000',
  '수용인원수': '184',
  '입장료': '무료',
  '숙박가능여부': 'Y',
  '주요시설명': '산림문화휴양관+숲속의집12동+연립동+야영센터+관리사무소+유아숲체험원',
  '소재지도로명주소': '충청북도 진천군 백곡면 명암길 435-135',
  '관리기관명': '충청북도 진천군청 산림축산과',
  '휴양림전화번호': '043-539-3554',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030033',
  '위도': '36.923988',
  '경도': '127.3902017',
  '데이터기준일자': '2023-07-05',
  '제공기관코드': '4450000',
  '제공기관명': '충청북도 진천군'},
 {'휴양림명': '여수봉황산자연휴양림',
  '시도명': '전라남도',
  '휴양림구분': '공유림',
  '휴양림면적': '2290000',
  '수용인원수': '230',
  '입장료': '0',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의집+야영장 등',
  '소재지도로명주소': '전라남도 여수시 돌산읍 대복길160',
  '관리기관명': '전라남도 여수시청',
  '휴양림전화번호': '061-643-9180',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030097',
  '위도': '34.61470237',
  '경도': '127.7617999',
  '데이터기준일자': '2023-07-05',
  '제공기관코드': '4810000',
  '제공기관명': '전라남도 여수시'},
 {'휴양림명': '고대산자연휴양림',
  '시도명': '경기도',
  '휴양림구분': '국유림',
  '휴양림면적': '314000',
  '수용인원수': '189',
  '입장료': '어른 : 개인1000원/단체 800원+청소년·군인 : 개인 800원/단체 600원+어린이 : 개인 500원/단체 300원',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의집 14동14실+산림휴양관 1동2층6실+숲속수련원 1동1실+방문자센터 1동2층 야영장데크 20개소',
  '소재지도로명주소': '경기도 연천군 신서면 고대산길 84-79',
  '관리기관명': '경기도 연천군청 산림녹지과',
  '휴양림전화번호': '031-834-2200',
  '홈페이지주소': 'https://godaesan.foresttrip.go.kr',
  '위도': '38.21125391',
  '경도': '127.1507058',
  '데이터기준일자': '2023-07-03',
  '제공기관코드': '4140000',
  '제공기관명': '경기도 연천군'},
 {'휴양림명': '간월산자연휴양림',
  '시도명': '울산광역시',
  '휴양림구분': '사유림',
  '휴양림면적': '597890',
  '수용인원수': '200',
  '입장료': '주중10~20만원+주말15~30만원',
  '숙박가능여부': 'Y',
  '주요시설명': '관리실+수영장+연수원',
  '소재지도로명주소': '울산광역시 울주군 상북면 작괘로 607-15',
  '관리기관명': '천광디엔씨',
  '휴양림전화번호': '052-263-6644',
  '홈페이지주소': 'https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/CmpngInfo/selectCmpngInfoList.do?mn=NKFS_03_01_01_02_04&restTpcd=01&restMngmeMnbdCd=003',
  '위도': '35.5670959',
  '경도': '129.0560416',
  '데이터기준일자': '2023-06-30',
  '제공기관코드': '3730000',
  '제공기관명': '울산광역시 울주군'},
 {'휴양림명': '용인자연휴양림',
  '시도명': '경기도',
  '휴양림구분': '공유림',
  '휴양림면적': '1801693',
  '수용인원수': '1800',
  '입장료': '개인성인2000원+개인청소년/군인/국가보훈대상자/다자녀가정1000원+개인어린이500원+단체성인1600원+단체청소년/군인/국가보훈대상자/다자녀가정800원+단체어린이400원',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의집+숲속체험관+목조주택+생태습지+야영장+잔디광장+짚라인+목재문화체험관 등',
  '소재지도로명주소': '경기도 용인시 처인구 모현면 초부로 220',
  '관리기관명': '경기도 용인시청',
  '휴양림전화번호': '031-336-0040',
  '홈페이지주소': 'https://yonginforest.foresttrip.go.kr/',
  '위도': '37.314713',
  '경도': '127.265315',
  '데이터기준일자': '2023-06-28',
  '제공기관코드': '4050000',
  '제공기관명': '경기도 용인시'},
 {'휴양림명': '제암산자연휴양림',
  '시도명': '전라남도',
  '휴양림구분': '공유림',
  '휴양림면적': '1600000',
  '수용인원수': '3000',
  '입장료': '개인(일반1000원+단체800원+할인500원)+청소년·군인(일반600원+단체500원+할인300원)+어린이(일반400원+단체300원+할인200원)',
  '숙박가능여부': 'Y',
  '주요시설명': '숙박+야영장+물놀이장+더늠길+숲속교육관+족구장데크+모험시설+하이데크+잔디광장',
  '소재지도로명주소': '전라남도 보성군 웅치면 대산길 330',
  '관리기관명': '전라남도 보성군청',
  '휴양림전화번호': '061-852-4434',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030090',
  '위도': '34.70050454',
  '경도': '126.9855053',
  '데이터기준일자': '2023-06-27',
  '제공기관코드': '4890000',
  '제공기관명': '전라남도 보성군'},
 {'휴양림명': '좌구산자연휴양림',
  '시도명': '충청북도',
  '휴양림구분': '공유림',
  '휴양림면적': '730000',
  '수용인원수': '250',
  '입장료': '없음',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의 집+황토집+별무리하우스+병영하우스+줄타기+썰매장+숲속모험시설+좌구산숲명상의집,+명상구름다리+좌구산천문대 등',
  '소재지도로명주소': '충청북도 증평군 증평읍 솟점말길 107',
  '관리기관명': '충청북도 증평군 휴양공원사업소',
  '휴양림전화번호': '043-835-4551',
  '홈페이지주소': 'https://jpjwagu.foresttrip.go.kr',
  '위도': '36.70556821',
  '경도': '127.6511216',
  '데이터기준일자': '2023-06-27',
  '제공기관코드': '5570000',
  '제공기관명': '충청북도 증평군'},
 {'휴양림명': '옥화자연휴양림',
  '시도명': '충청북도',
  '휴양림구분': '공유림',
  '휴양림면적': '862790',
  '수용인원수': '373',
  '입장료': '어른(개인 1000원+단체 500원)+청소년(개인 500원+단체 300원)+어린이(개인 300원+단체 200원)+군인(개인 500원+단체 300원)+지역주민(개인 500원+단체 300원)',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의집+산림휴양관+국민여가오토캠핑장+물놀이장 등',
  '소재지도로명주소': '충청북도 청주시 상당구 미원면 운암옥화길 140',
  '관리기관명': '청주시 푸른도시사업본부',
  '휴양림전화번호': '043-270-7384',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030054',
  '위도': '36.59895012',
  '경도': '127.6943716',
  '데이터기준일자': '2023-06-26',
  '제공기관코드': '5710000',
  '제공기관명': '충청북도 청주시'},
 {'휴양림명': '동두천자연휴양림',
  '시도명': '경기도',
  '휴양림구분': '공유림',
  '휴양림면적': '700000',
  '수용인원수': '1000',
  '입장료': '성인2000+청소년구인1500+아동1000',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의집+야외데크+치유의숲+유아숲체험원',
  '소재지도로명주소': '경기도 동두천시 탑동가산로 1',
  '관리기관명': '경기도 동두천시청 관광휴양과',
  '휴양림전화번호': '031-860-3256',
  '홈페이지주소': 'https://blog.naver.com/ddcforest',
  '위도': '37.88988548',
  '경도': '127.1371472',
  '데이터기준일자': '2023-06-23',
  '제공기관코드': '3920000',
  '제공기관명': '경기도 동두천시'},
 {'휴양림명': '서귀포자연휴양림',
  '시도명': '제주특별자치도',
  '휴양림구분': '국유림',
  '휴양림면적': '2550000',
  '수용인원수': '1500',
  '입장료': '어른 1000원+청소년 600원+어린이 300원+(단체)어른 800원+(단체)청소년 500원+(단체)어린이 200원',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의집+산림휴양관+세미나실+야영장+생태탐방코스',
  '소재지도로명주소': '제주특별자치도 서귀포시 1100로 882',
  '관리기관명': '제주특별자치도 서귀포시청',
  '휴양림전화번호': '064-738-4544',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030013',
  '위도': '33.3115002',
  '경도': '126.458761',
  '데이터기준일자': '2023-06-13',
  '제공기관코드': '6520000',
  '제공기관명': '제주특별자치도 서귀포시'},
 {'휴양림명': '붉은오름자연휴양림',
  '시도명': '제주특별자치도',
  '휴양림구분': '공유림',
  '휴양림면적': '1900000',
  '수용인원수': '1500',
  '입장료': '어른 1000원+청소년·군인 600원+(단체)어른 800원+(단체)청소년·군인 500원',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의집+산림문화휴양관+세미나실+오름등반로+야외공연장',
  '소재지도로명주소': '제주특별자치도 서귀포시 표선면 남조로 1487-73',
  '관리기관명': '제주특별자치도 서귀포시청',
  '휴양림전화번호': '064-760-3481',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030014',
  '위도': '33.401429',
  '경도': '126.675671',
  '데이터기준일자': '2023-06-13',
  '제공기관코드': '6520000',
  '제공기관명': '제주특별자치도 서귀포시'},
 {'휴양림명': '서귀포 치유의 숲',
  '시도명': '제주특별자치도',
  '휴양림구분': '공유림',
  '휴양림면적': '1740000',
  '수용인원수': '600',
  '입장료': '어른 1000원+청소년 600원+(단체)어른 800원+(단체)청소년 500원',
  '숙박가능여부': 'N',
  '주요시설명': '치유숲길',
  '소재지도로명주소': '제주특별자치도 서귀포시 산록남로 2271',
  '관리기관명': '제주특별자치도 서귀포시청',
  '휴양림전화번호': '064-760-3067',
  '홈페이지주소': 'https://seogwipo.go.kr/healing/index.htm',
  '위도': '33.291941',
  '경도': '126.527902',
  '데이터기준일자': '2023-06-13',
  '제공기관코드': '6520000',
  '제공기관명': '제주특별자치도 서귀포시'},
 {'휴양림명': '칠갑산자연휴양림',
  '시도명': '충청남도',
  '휴양림구분': '공유림',
  '휴양림면적': '73000',
  '수용인원수': '500',
  '입장료': '개인 일반 1000원 +개인 청소년·군인 800원+개인 어린이 500원+단체 일반 800원+단체 청소년·군인 600원+단체 어린이 300원 + 청양 부여 공주 군(시)민 무료',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의 집+산림문화 휴양관+원두막+기타시설 등',
  '소재지도로명주소': '충청남도 청양군 대치면 칠갑산로 668-103',
  '관리기관명': '충청남도 청양군공공시설사업소',
  '휴양림전화번호': '041-940-2429',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030044',
  '위도': '36.431589',
  '경도': '126.8438227',
  '데이터기준일자': '2023-06-22',
  '제공기관코드': '4590000',
  '제공기관명': '충청남도 청양군'},
 {'휴양림명': '치악산자연휴양림',
  '시도명': '강원도',
  '휴양림구분': '공유림',
  '휴양림면적': '1700000',
  '수용인원수': '120',
  '입장료': '일반(개인 2000+청소년 및 군인 1500+어린이 1000)+단체(어른 1500+청소년 및 군인 1000+어린이 700)',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의집+주차장+산책로',
  '소재지도로명주소': '강원도 원주시 판부면 휴양림길 66',
  '관리기관명': '강원도 원주시청 산림과',
  '휴양림전화번호': '033-762-8288',
  '홈페이지주소': 'https://foresttrip.go.kr/indvz/main.do?hmpgId=ID02030024',
  '위도': '37.255878',
  '경도': '128.031372',
  '데이터기준일자': '2023-02-06',
  '제공기관코드': '4190000',
  '제공기관명': '강원도 원주시'},
 {'휴양림명': '숲체원',
  '시도명': '강원도',
  '휴양림구분': '국유림',
  '휴양림면적': '159710',
  '수용인원수': '300',
  '입장료': '별도 입장료 없음',
  '숙박가능여부': 'Y',
  '주요시설명': '탐방로, 숙박동, 강의실',
  '소재지도로명주소': '강원도 횡성군 둔내면 청태산로 777',
  '관리기관명': '산림청',
  '휴양림전화번호': '033-340-6300',
  '홈페이지주소': 'https://hoengseong.fowi.or.kr/',
  '위도': '37.53722046',
  '경도': '128.2866886',
  '데이터기준일자': '2022-06-22',
  '제공기관코드': '4260000',
  '제공기관명': '강원도 횡성군'},
 {'휴양림명': '청태산휴양림',
  '시도명': '강원도',
  '휴양림구분': '국유림',
  '휴양림면적': '159520',
  '수용인원수': '1500',
  '입장료': '일반 : 1000원+청소년 : 600원+어린이 : 300원',
  '숙박가능여부': 'Y',
  '주요시설명': '제1산림문화휴양관, 제2산림문화휴양관, 숲속의집, 숲속수련장(중형, 소형), 대형숲속수영장(회의실), 야영장, 인도네시아 전통 전시관, 숲생태체험실, BIY목공교실',
  '소재지도로명주소': '강원도 횡성군 둔내면 청태산로 610',
  '관리기관명': '산림청',
  '휴양림전화번호': '033-343-9707',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=0106',
  '위도': '37.52907993',
  '경도': '128.2968658',
  '데이터기준일자': '2022-06-22',
  '제공기관코드': '4260000',
  '제공기관명': '강원도 횡성군'},
 {'휴양림명': '민주지산자연휴양림',
  '시도명': '충청북도',
  '휴양림구분': '공유림',
  '휴양림면적': '1800000',
  '수용인원수': '394',
  '입장료': '어른 1000원+청소년 500원+어린이 300원',
  '숙박가능여부': 'N',
  '주요시설명': '버섯동+생화동+국악동+식당+황토방+황토찝질방+학습관+너와집+산림문화휴양관1,2층 세미나실+치유숙소6개소+치유센터+진료동+치유센터치유동+야외 치유시설+야영장+족구장 등',
  '소재지도로명주소': '충청북도 영동군 용화면 휴양림길 60',
  '관리기관명': '충청북도 영동군청 산림과',
  '휴양림전화번호': '043-740-3437',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030107',
  '위도': '36.05313182',
  '경도': '127.8243888',
  '데이터기준일자': '2022-11-30',
  '제공기관코드': '4440000',
  '제공기관명': '충청북도 영동군'},
 {'휴양림명': '태백고원자연휴양림',
  '시도명': '강원도',
  '휴양림구분': '국유림',
  '휴양림면적': '1404000',
  '수용인원수': '110',
  '입장료': '2000원',
  '숙박가능여부': 'Y',
  '주요시설명': '산림문화휴양관, 숲속의 집 , 야영장',
  '소재지도로명주소': '강원도 태백시 머리골길153',
  '관리기관명': '태백시농업기술센터 산림축산과',
  '휴양림전화번호': '033-550-2849',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030022',
  '위도': '37.12357654',
  '경도': '129.0603832',
  '데이터기준일자': '2023-04-05',
  '제공기관코드': '4220000',
  '제공기관명': '강원도 태백시'},
 {'휴양림명': '교래자연휴양림',
  '시도명': '제주특별자치도',
  '휴양림구분': '공유림',
  '휴양림면적': '230',
  '수용인원수': '1500',
  '입장료': '어른1000원+청소년600원+군인600원+단체어른800원+단체청소년500원+단체군인500원',
  '숙박가능여부': 'Y',
  '주요시설명': '휴양림+숙박+공연장등',
  '소재지도로명주소': '제주특별자치도 제주시 조천읍 남조로 2023',
  '관리기관명': '제주특별자치도청',
  '휴양림전화번호': '064-783-7482',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030056',
  '위도': '33.45136376',
  '경도': '126.6567109',
  '데이터기준일자': '2023-07-06',
  '제공기관코드': '6510000',
  '제공기관명': '제주특별자치도 제주시'},
 {'휴양림명': '태학산자연휴양림',
  '시도명': '충청남도',
  '휴양림구분': '공유림',
  '휴양림면적': '1055598',
  '수용인원수': '1000',
  '입장료': '없음',
  '숙박가능여부': 'N',
  '주요시설명': '숲속의집+잔디광장+숲속공연장 등',
  '소재지도로명주소': '충청남도 천안시 동남구 풍세면 휴양림길 127',
  '관리기관명': '충청남도 천안시청',
  '휴양림전화번호': '041-529-5108',
  '홈페이지주소': 'http://www.cfmc.or.kr/_taehaksan/',
  '위도': '36.72734819',
  '경도': '127.0903273',
  '데이터기준일자': '2023-06-30',
  '제공기관코드': '4490000',
  '제공기관명': '충청남도 천안시'},
 {'휴양림명': '비학산자연휴양림',
  '시도명': '경상북도',
  '휴양림구분': '공유림',
  '휴양림면적': '2280000',
  '수용인원수': '150',
  '입장료': '숙박 : 7만원 + 11만원+ 14만원',
  '숙박가능여부': 'Y',
  '주요시설명': '산림휴양관+숲속의 집+테라스하우스+카라반+야외데크+생태숲 등',
  '소재지도로명주소': '경상북도 포항시 북구 기북면 비학산길 302',
  '관리기관명': '경상북도 포항시청',
  '휴양림전화번호': '054-252-3275',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030052',
  '위도': '36.14703337',
  '경도': '129.2111071',
  '데이터기준일자': '2023-07-06',
  '제공기관코드': '5020000',
  '제공기관명': '경상북도 포항시'},
 {'휴양림명': '성불산자연휴양림',
  '시도명': '충청북도',
  '휴양림구분': '공유림',
  '휴양림면적': '58',
  '수용인원수': '242',
  '입장료': '입장료 개인(어린이 1000원+청소년 1500원+군인 1500원+일반 2000원)+입장료 단체(30명 이상)(어린이 500원+청소년 1000원+군인 1000원+일반 1500원)+주차료(경형 1500원+중소형 3000원+대형 5000원+숙박시설 사용자 무료)',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의집A+숲속의집B+산림문화휴양관+숲관광메가시티+생태숲학습관+한옥체험관+생태공원+미선향테마파크무인카페+수석전시관 등',
  '소재지도로명주소': '충청북도 괴산군 괴산읍 충민로기곡길 78',
  '관리기관명': '충청북도 괴산군청 산림녹지과',
  '휴양림전화번호': '043-830-2679',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030070',
  '위도': '36.80804701',
  '경도': '127.8467688',
  '데이터기준일자': '2023-07-10',
  '제공기관코드': '4460000',
  '제공기관명': '충청북도 괴산군'},
 {'휴양림명': '비슬산자연휴양림',
  '시도명': '대구광역시',
  '휴양림구분': '공유림',
  '휴양림면적': '1000000',
  '수용인원수': '285',
  '입장료': '없음',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의집+통나무집+야영장+반딧불이전기차등',
  '소재지도로명주소': '대구광역시 달성군 유가읍 일연선사길 99',
  '관리기관명': '대구광역시 달성군시설관리공단',
  '휴양림전화번호': '053-659-4400',
  '홈페이지주소': 'http://bisulsan.dssiseol.or.kr/bisulsan/html/main.html',
  '위도': '35.69001083',
  '경도': '128.5129017',
  '데이터기준일자': '2023-07-10',
  '제공기관코드': '3480000',
  '제공기관명': '대구광역시 달성군'},
 {'휴양림명': '화원자연휴양림',
  '시도명': '대구광역시',
  '휴양림구분': '공유림',
  '휴양림면적': '720000',
  '수용인원수': '115',
  '입장료': '없음',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의집+산림문화휴양관+산림욕장+전망데크등',
  '소재지도로명주소': '대구광역시 달성군 화원읍 화원휴양림길 126',
  '관리기관명': '대구광역시 달성군시설관리공단',
  '휴양림전화번호': '053-659-4455',
  '홈페이지주소': 'http://hwawon.dssiseol.or.kr/hwawon/html/main.html',
  '위도': '35.77179173',
  '경도': '128.5367385',
  '데이터기준일자': '2023-07-10',
  '제공기관코드': '3480000',
  '제공기관명': '대구광역시 달성군'},
 {'휴양림명': '천보산자연휴양림',
  '시도명': '경기도',
  '휴양림구분': '공유림',
  '휴양림면적': '1165686',
  '수용인원수': '80',
  '입장료': '일반 2000원+단체 1400원',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의집+휴양관+야영장 등',
  '소재지도로명주소': '경기도 포천시 원동교길 309',
  '관리기관명': '경기도 포천시청',
  '휴양림전화번호': '031-538-3554',
  '홈페이지주소': '',
  '위도': '37.85576406',
  '경도': '127.1190897',
  '데이터기준일자': '2023-07-07',
  '제공기관코드': '5600000',
  '제공기관명': '경기도 포천시'},
 {'휴양림명': '국망봉자연휴양림',
  '시도명': '경기도',
  '휴양림구분': '사유림',
  '휴양림면적': '2554814',
  '수용인원수': '60',
  '입장료': '관람객 5000원+등산객2000원',
  '숙박가능여부': 'Y',
  '주요시설명': '통나무 집+캠핑장 등',
  '소재지도로명주소': '경기도 포천시 이동면 늠바위길 207-28',
  '관리기관명': '김봉일',
  '휴양림전화번호': '031-532-0014',
  '홈페이지주소': 'www.kookmang.co.kr',
  '위도': '38.02891868',
  '경도': '127.3962681',
  '데이터기준일자': '2023-07-07',
  '제공기관코드': '5600000',
  '제공기관명': '경기도 포천시'},
 {'휴양림명': '안면도자연휴양림',
  '시도명': '충청남도',
  '휴양림구분': '국유림',
  '휴양림면적': '1350000',
  '수용인원수': '6000',
  '입장료': '일반 1000원+청소년 800원+군인 800원+어린이 400원',
  '숙박가능여부': 'Y',
  '주요시설명': '전시관+수목원+숲속의집 등',
  '소재지도로명주소': '충청남도 태안군 안면읍 안면대로3195-6',
  '관리기관명': '충청남도 산림환경연구소 휴양림관리사무소',
  '휴양림전화번호': '041-674-5019',
  '홈페이지주소': 'www.anmyonhuyang.go.kr',
  '위도': '36.49670127',
  '경도': '126.3588291',
  '데이터기준일자': '2023-07-05',
  '제공기관코드': '4620000',
  '제공기관명': '충청남도 태안군'},
 {'휴양림명': '변산자연휴양림',
  '시도명': '전라북도',
  '휴양림구분': '국유림',
  '휴양림면적': '311000',
  '수용인원수': '250',
  '입장료': '숙박비 52000원+154000원',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의집+휴양관+체험교실+물놀이장(현재 미운영)',
  '소재지도로명주소': '전라북도 부안군 변산면 변산로 3768',
  '관리기관명': '국립자연휴양림관리소',
  '휴양림전화번호': '063-581-9977',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=0189',
  '위도': '35.58287781',
  '경도': '126.523728',
  '데이터기준일자': '2023-08-24',
  '제공기관코드': '4790000',
  '제공기관명': '전라북도 부안군'},
 {'휴양림명': '축령산자연휴양림',
  '시도명': '경기도',
  '휴양림구분': '공유림',
  '휴양림면적': '7790000',
  '수용인원수': '172',
  '입장료': '일반1000원+청소년 600원+어린이 300원',
  '숙박가능여부': 'Y',
  '주요시설명': '숲속의집 7실+산림휴양관18실+축령관 1실+야영데크30개 등',
  '소재지도로명주소': '경기도 남양주시 수동면 축령산로 299',
  '관리기관명': '경기도산림환경연구소',
  '휴양림전화번호': '031-8030-6690',
  '홈페이지주소': 'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030050',
  '위도': '37.7547680401',
  '경도': '127.3132530480',
  '데이터기준일자': '2023-09-05',
  '제공기관코드': '6410000',
  '제공기관명': '경기도'},
 {'휴양림명': '강씨봉자연휴양림',
  '시도명': '경기도',
  '휴양림구분': '공유림',
  '휴양림면적': '9800000',
  '수용인원수': '102',
  '입장료': '일반1000원+청소년 600원+어린이 300원',

In [ ]:
pdData = pd.DataFrame(data)
pdData

,휴양림명,시도명,휴양림구분,휴양림면적,수용인원수,입장료,숙박가능여부,주요시설명,소재지도로명주소,관리기관명,휴양림전화번호,홈페이지주소,위도,경도,데이터기준일자,제공기관코드,제공기관명
0,광치자연휴양림,강원도,공유림,51,160,3000원,Y,"숲속의집, 휴양관, 숲속카페,무장애나눔길",강원도 양구군 남면 광치령로 1794번길 265,강원도 양구군청,033-482-3115,http://www.foresttrip.go.kr,38.14199686,128.0710755,2022-08-31,4320000,강원도 양구군
1,삼척활기자연휴양림,강원도,사유림,75625,175,0,Y,휴양관(송폭헌)+ 한옥(방우재)+ 한옥(세우재)+숲속의집(구희당)+숲속의집(삼락당),강원도 삼척시 미로면 준경길 651-43(지번활기리 403-1),삼척동해태백산림조합,033-574-0032,https://www.foresttrip.go.kr/indvz/main.do?hmp...,37.38099374,129.0601226,2023-01-04,4240000,강원도 삼척시
2,데미샘자연휴양림,전라북도,공유림,200000,131,무료,Y,휴양관+숲속의집+숲문화마당+명상의숲 등,전라북도 진안군 백운면 데미샘 1길 172,전라북도 산림환경연구소,063-290-6992,https://www.foresttrip.go.kr/indvz/main.do?hmp...,35.656988,127.461036,2023-02-27,6450000,전라북도
3,강릉임해자연휴양림,강원도,공유림,1160000,105,비수기 평일[(6인실)70000원+(5인실)65000원+(4인실)50000원]+비수...,Y,숙박동(하늘동+구름동+바다동+숲속동)+숲속의집,강원도 강릉시 강동면 율곡로 1715-85,강릉관광개발공사,033-644-9483,https://www.foresttrip.go.kr/indvz/main.do?hmp...,37.71856556,128.9985453,2023-03-15,4200000,강원도 강릉시
4,금강자연휴양림,충청남도,공유림,1840000,226,1500,Y,숲속의 집+휴양관+야영장,세종특별자치시 금남면 산림박물관길110,산림자원연구소,041-635-7400,keumkang.chungnam.go.kr,36.43769938,127.2327429,2023-03-24,6440000,충청남도
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,좌구산자연휴양림,충청북도,공유림,730000,251,무료,Y,숲속의집+황토집+별무리하우스+병영하우스+율리휴양촌+오토캠핑장+족구장,충청북도 증평군 증평읍 솟점말길 107,충청북도 증평군청,043-835-4581,,36.70556821,127.6511216,2023-08-01,6430000,충청북도
209,횡성자연휴양림,강원도,사유림,498263,300,숙박시설 이용객만 입장 가능(별도입장료 : 없음),Y,"숲속의집, 산림문화휴양관",강원도 횡성군 갑천면 정포로 430번길 113,사유휴양림(대표 : 이호준),033-343-3392,http://www.hsrf.co.kr,37.53904383,128.1118525,2022-06-22,4261000,강원특별자치도 횡성군
210,주천강자연휴양림,강원도,사유림,2296100,400,숙박시설 이용객만 입장 가능(별도입장료 : 없음),Y,"숲속마을, 산골마을, 강변마을, 숲속학교, 황토별장",강원도 횡성군 둔내면 강변로 영랑6길 115,사유휴양림(대표 : 김문기),033-345-7575,http://jucheon.com/,37.4606019,128.2034233,2022-06-22,4261000,강원특별자치도 횡성군
211,숲체원,강원도,국유림,159710,300,별도 입장료 없음,Y,"탐방로, 숙박동, 강의실",강원도 횡성군 둔내면 청태산로 777,산림청,033-340-6300,https://hoengseong.fowi.or.kr/,37.53722046,128.2866886,2022-06-22,4261000,강원특별자치도 횡성군
212,청태산휴양림,강원도,국유림,159520,1500,일반 : 1000원+청소년 : 600원+어린이 : 300원,Y,"제1산림문화휴양관, 제2산림문화휴양관, 숲속의집, 숲속수련장(중형, 소형), 대형숲...",강원도 횡성군 둔내면 청태산로 610,산림청,033-343-9707,https://www.foresttrip.go.kr/indvz/main.do?hmp...,37.52907993,128.2968658,2022-06-22,4261000,강원특별자치도 횡성군

In [ ]:
outputFile = '자연휴양림출력화일.xlsx'
pdData.to_excel(outputFile)

In [20]:
import folium
folium.Map()

In [22]:
a = folium.Map(location=[37.448028, 127.169366])
a

In [24]:
a = folium.Map(location=[37.448028, 127.169366],zoom_start=13)
a

In [27]:
a = folium.Map(location=[37.448028, 127.169366],zoom_start=13,zoom_control=False)
a

In [28]:
a = folium.Map(location=[37.448028, 127.169366],
               zoom_start=13,
               zoom_control=False,
               control_scale=True)
a

In [44]:
map = folium.Map(location=[37.4965, 126.9573],
                 zoom_start=15,
                 zoom_control=False,
                 control_scale=True,
                 tiles='OpenStreetMap')

In [45]:
map

In [46]:
mk5 = folium.Circle([37.53,126.97],popup = '위치5',color='green')
mk5.add_to(map)

In [47]:
map

In [48]:
df = pd.read_excel('/content/자연휴양림출력화일.xlsx')
df.head()

,Unnamed: 0,휴양림명,시도명,휴양림구분,휴양림면적,수용인원수,입장료,숙박가능여부,주요시설명,소재지도로명주소,관리기관명,휴양림전화번호,홈페이지주소,위도,경도,데이터기준일자,제공기관코드,제공기관명
0,0,광치자연휴양림,강원도,공유림,51.0,160.0,3000원,Y,"숲속의집, 휴양관, 숲속카페,무장애나눔길",강원도 양구군 남면 광치령로 1794번길 265,강원도 양구군청,033-482-3115,http://www.foresttrip.go.kr,38.141997,128.071076,2022-08-31,4320000,강원도 양구군
1,1,삼척활기자연휴양림,강원도,사유림,75625.0,175.0,0,Y,휴양관(송폭헌)+ 한옥(방우재)+ 한옥(세우재)+숲속의집(구희당)+숲속의집(삼락당),강원도 삼척시 미로면 준경길 651-43(지번활기리 403-1),삼척동해태백산림조합,033-574-0032,https://www.foresttrip.go.kr/indvz/main.do?hmp...,37.380994,129.060123,2023-01-04,4240000,강원도 삼척시
2,2,데미샘자연휴양림,전라북도,공유림,200000.0,131.0,무료,Y,휴양관+숲속의집+숲문화마당+명상의숲 등,전라북도 진안군 백운면 데미샘 1길 172,전라북도 산림환경연구소,063-290-6992,https://www.foresttrip.go.kr/indvz/main.do?hmp...,35.656988,127.461036,2023-02-27,6450000,전라북도
3,3,강릉임해자연휴양림,강원도,공유림,1160000.0,105.0,비수기 평일[(6인실)70000원+(5인실)65000원+(4인실)50000원]+비수...,Y,숙박동(하늘동+구름동+바다동+숲속동)+숲속의집,강원도 강릉시 강동면 율곡로 1715-85,강릉관광개발공사,033-644-9483,https://www.foresttrip.go.kr/indvz/main.do?hmp...,37.718566,128.998545,2023-03-15,4200000,강원도 강릉시
4,4,금강자연휴양림,충청남도,공유림,1840000.0,226.0,1500,Y,숲속의 집+휴양관+야영장,세종특별자치시 금남면 산림박물관길110,산림자원연구소,041-635-7400,keumkang.chungnam.go.kr,36.437699,127.232743,2023-03-24,6440000,충청남도

In [49]:
anMap = folium.Map(location=[37.4965, 126.9573],
                   zoom_start=11,
                   zoom_control=False,
                   control_scale=True)
anMap

In [52]:
for n, row in df.iterrows():
  print(n,row['휴양림명'],row['위도'],row['경도'])

0 광치자연휴양림 38.14199686 128.0710755
1 삼척활기자연휴양림 37.38099374 129.0601226
2 데미샘자연휴양림 35.656988 127.461036
3 강릉임해자연휴양림 37.71856556 128.9985453
4 금강자연휴양림 36.43769938 127.2327429
5 보현산자연휴양림 36.14210706 128.9781098
6 만수산자연휴양림 36.33854208 126.7119325
7 남해편백자연휴양림(남해) 34.75216391 128.0201321
8 지리산자연휴양림(함양) 35.34644465 127.6430043
9 원동자연휴양림(양산) 35.39881801 128.9348445
10 덕원자연휴양림(하동) 35.22915471 127.8552761
11 중산자연휴양림(산청) 35.2886177 127.7507425
12 생거진천자연휴양림 36.923988 127.3902017
13 여수봉황산자연휴양림 34.61470237 127.7617999
14 고대산자연휴양림 38.21125391 127.1507058
15 간월산자연휴양림 35.5670959 129.0560416
16 용인자연휴양림 37.314713 127.265315
17 제암산자연휴양림 34.70050454 126.9855053
18 좌구산자연휴양림 36.70556821 127.6511216
19 옥화자연휴양림 36.59895012 127.6943716
20 동두천자연휴양림 37.88988548 127.1371472
21 서귀포자연휴양림 33.3115002 126.458761
22 붉은오름자연휴양림 33.401429 126.675671
23 서귀포 치유의 숲 33.291941 126.527902
24 칠갑산자연휴양림 36.431589 126.8438227
25 치악산자연휴양림 37.255878 128.031372
26 숲체원 37.53722046 128.2866886
27 청태산휴양림 37.52907993 128.2968658
28 민주지산자연휴양림 36.05313182 127.8243888
29 태백고원자연휴양림 37.12357654 129.0603832
30 교래자연휴양림 33.45136376 126.6567109
31 태학산자연휴양림 36.72734819 127.0903273
32 비학산자연휴양림 36.14703337 129.2111071
33 성불산자연휴양림 36.80804701 127.8467688
34 비슬산자연휴양림 35.69001083 128.5129017
35 화원자연휴양림 35.77179173 128.5367385
36 천보산자연휴양림 37.85576406 127.1190897
37 국망봉자연휴양림 38.02891868 127.3962681
38 안면도자연휴양림 36.49670127 126.3588291
39 변산자연휴양림 35.58287781 126.523728
40 축령산자연휴양림 37.7547680401 127.313253048
41 강씨봉자연휴양림 37.9698930209 127.4083285104
42 청송자연휴양림 36.3179023 129.0537598
43 송이밸리자연휴양림 38.05400667 128.6214924
44 자굴산 자연휴양림 35.377313 128.208971
45 유치자연휴양림 34.76806521 126.8323492
46 입화산 자연휴양림 35.578739 129.279479
47 회문산자연휴양림 35.50195867 127.1148251
48 용궐산자연휴양림 35.46166861 127.2048302
49 주천강자연휴양림 37.4606019 128.2034233
50 성주산자연휴양림 36.33256882 126.6639659
51 박달재자연휴양림 37.14706386 128.0457749
52 옥전자연휴양림 37.17540371 128.0899438
53 흥부골자연휴양림 35.450932 127.590258
54 남원자연휴양림 35.458117 127.415508
55 세심자연휴양림 35.514241 127.240066
56 미숭산자연휴양림 35.75077545 128.2028394
57 봉수산자연휴양림 36.59844872 126.7808937
58 문수산 산림욕장 37.737829 126.5308885
59 국립신시도자연휴양림 35.82815579 126.4468419
60 데미샘자연휴양림 35.6569938 127.4610402
61 운장산자연휴양림 35.89924607 127.4211096
62 송이밸리자연휴양림 38.05400667 128.6214924
63 구재봉자연휴양림 35.12895794 127.7440937
64 평창자연휴양림 37.609548 128.303521
65 동강전망자연휴양림 37.25962318 128.6079002
66 바라산자연휴양림 37.37310185 127.0193147
67 거제자연휴양림 34.7856966 128.625968
68 운주산승마자연휴양림 36.03510258 128.996734
69 산수유자연휴양림 35.3009035312 127.4626986897
70 주작산자연휴양림 34.5172932 126.6989685
71 삼척활기자연휴양림 37.38099374 129.0601226
72 충북알프스자연휴양림 36.57316547 127.7858442
73 속리산 숲체험휴양마을 36.49245442 127.792472
74 장령산자연휴양림 36.24486737 127.5547497
75 국립용지봉자연휴양림 35.18905366 128.7741351
76 영양에코둥지 36.70182591 129.1124232
77 불정자연휴양림 36.62128207 128.1365074
78 대야산자연휴양림 36.67090364 127.9619774
79 소선암자연휴양림 36.91922142 128.3123127
80 소백산자연휴양림 37.06069296 128.4673084
81 군위장곡자연휴양림 36.129815 128.835924
82 독용산성 자연휴양림 35.90636795 128.1344115
83 가리산자연휴양림 37.8656358 127.9811498
84 문성자연휴양림 37.02832486 127.7525206
85 봉황자연휴양림 37.05652102 127.8297473
86 계명산자연휴양림 36.9793629 127.9950872
87 옥성자연휴양림 36.27907203 128.2844292
88 오도산 자연휴양림 35.66904355 128.0538747
89 대운산자연휴양림 35.4178546195 129.2088997535
90 용봉산자연휴양림 36.64528712 126.6566318
91 계명산자연휴양림 36.41012056 128.9465131
92 강릉임해자연휴양림 37.71856556 128.9985453
93 수도산 자연휴양림 35.8918024 127.9838463
94 하추자연휴양림 38.03469483 128.3193078
95 금산산림문화타운 36.06776064 127.3690934
96 진산자연휴양림 36.12303243 127.3441498
97 서대산약용자연휴양림 36.22268671 127.5258197
98 심천치유자연휴양림 35.99504733 127.4849511
99 신안자연휴양관 34.87971569 125.9954724
100 가리산자연휴양림 37.8656358003 127.9811498126
101 아세안자연휴양림 37.77382293 126.9421758
102 장흥 자연휴양림 37.75816692 126.9685293
103 팔공산금화자연휴양림 36.05171899 128.5553512
104 안동호반자연휴양림 36.70343807 128.8288547
105 토함산자연휴양림 35.76176465 129.3649053
106 화왕산자연휴양림(창녕) 35.54693079 128.5673145
107 구재봉자연휴양림(하동) 35.12895794 127.7440937
108 하동편백자연휴양림 35.18703884 127.8398597
109 한방자연휴양림(산청) 35.43403584 127.8236808
110 용추자연휴양림(함양) 35.69613134 127.7578619
111 대봉산자연휴양림(함양) 35.57794015 127.7150289
112 산삼자연휴양림(함양) 35.69762459 127.6584297
113 금원산자연휴양림(거창) 35.72617571 127.795727
114 항노화자연휴양림(항노화힐링랜드) 35.73662049 128.0408983
115 오도산자연휴양림(합천) 35.66904518 128.0538745
116 산삼휴양밸리(대봉캠핑랜드) 35.58818277 127.6790131
117 용지봉자연휴양림(김해) 35.18540272 128.7754769
118 하동편백자연휴양림 35.1858764 127.8484386
119 하추자연휴양림 38.03469483 128.3193078
120 치악산자연휴양림 37.255878 128.031372
121 거제자연휴양림 34.78569918 128.6259431
122 동강전망자연휴양림 37.25962318 128.6079002
123 금봉자연휴양림 36.3360183 128.8807891
124 광치자연휴양림 38.14199686 128.0710755
125 거창 항노화 힐링랜드 35.73662049 128.0408983
126 문수산자연휴양림 36.950851 128.834816
127 학가산우래자연휴양림 36.677929 128.592876
128 만인산자연휴양림 36.2021806 127.4551104
129 장태산자연휴양림 36.21596742 127.3412777
130 팔영산자연휴양림 34.62133127 127.4401371
131 두루웰자연휴양림 38.227936 127.353297
132 군위장곡자연휴양림 36.129815 128.835924
133 양을산산림욕장 34.8213604 126.4075568
134 밀양도래재자연휴양림 35.55632931 128.9390583
135 수레의산자연휴양림 37.03888889 127.6513842
136 백야자연휴양림 36.95683951 127.6096488
137 한방자연휴양림 35.43403493 127.8236813
138 백운산자연휴양림 35.05164287 127.5985311
139 절물자연휴양림 33.44004881 126.6252034
140 춘천숲자연휴양림 37.747732 127.742503
141 송정자연휴양림 36.02333423 128.4416412
142 성주봉자연휴양림 36.53359844 128.0407595
143 유명산자연휴양림 37.5929359 127.4910626
144 강씨봉자연휴양림 37.9698930209 127.4083149
145 칼봉산자연휴양림 37.8365192 127.4651587
146 청평자연휴양림 37.7118010733 127.4072397117
147 진주 월아산 자연휴양림 35.19991568 128.1941259
148 국립방장산자연휴양림 35.3688011979 126.7314611534
149 방장산자연휴양림 35.44405218 126.7514053
150 흑석산자연휴양림 34.67093468 126.6169967
151 백아산자연휴양림 35.15137582 127.1671251
152 한천자연휴양림 34.98834125 127.0454803
153 영인산자연휴양림 36.84059456 126.9500195
154 양촌자연휴양림 36.15726044 127.2464846
155 화왕산자연휴양림 35.54697823 128.5673185
156 함평자연생태공원 35.13500123 126.5056999542
157 순천자연휴양림 35.04388083 127.4744949
158 사천 케이블카 자연휴양림 34.95016897 128.0576108
159 남해편백자연휴양림 34.75216391 128.0201316
160 운문산자연휴양림 35.64834675 129.026208
161 고산자연휴양림 35.96224205 127.2328719
162 용추자연휴양림 35.6961266 127.7578596
163 산삼자연휴양림 35.69762431 127.6584311
164 대봉산자연휴양림 35.57794141 127.7150294
165 월아산자연휴양림(진주) 35.199915 128.1941257
166 사천케이블카자연휴양림(사천) 34.95015858 128.0583444
167 도래재자연휴양림(밀양) 35.55632931 128.9390583
168 거제자연휴양림(거제) 34.78569918 128.6259431
169 대운산자연휴양림(양산) 35.41785462 129.2088998
170 자굴산자연휴양림(의령) 35.37763031 128.2089972
171 생거진천자연휴양림 36.92399609 127.3902346
172 성불산자연휴양림 36.80804701 127.8467688
173 수레의산자연휴양림 37.03888915 127.6513855
174 백야자연휴양림 36.95683852 127.6096498
175 소선암자연휴양림 36.91922142 128.3123127
176 소백산자연휴양림 37.06069296 128.4673084
177 조령산자연휴양림 36.81234006 128.0462438
178 구름산산림욕장 37.454013 126.876365
179 횡성자연휴양림 37.53904383 128.1118525
180 반딧불 자연휴양림 36.0124904721 127.7611880914
181 강화군 석모도자연휴양림 37.69963904 126.3154373
182 강화군 티앤림 자연휴양림 37.71482742 126.453839
183 용문산자연휴양림 37.516048 127.519421
184 양평쉬자파크 37.511222 127.533196
185 설매재자연휴양림 37.556802 127.509356
186 서운산자연휴양림 36.94238317 127.313722
187 태백고원자연휴양림 37.12357654 129.0603832
188 불갑사 관광휴양단지 35.202988 126.5367799663
189 구수곡자연휴양림 37.06212162 129.2929279
190 평창자연휴양림 37.609548 128.303521
191 와룡자연휴양림 35.67621885 127.4772179
192 방화동가족휴가촌 35.59064044 127.5268764
193 방화동자연휴양림 35.59064044 127.5268764
194 공주산림휴양마을 36.42442578 127.1193201
195 국립희리산해송자연휴양림 36.11262716 126.664181
196 두루웰자연휴양림 38.227936 127.353297
197 춘천숲자연휴양림 37.747732 127.742503
198 옥화자연휴양림 36.59895012 127.6943716
199 문성자연휴양림 37.02832602 127.7525217
200 봉황자연휴양림 37.05652228 127.8297465
201 계명산자연휴양림 36.97931793 127.9950865
202 박달재자연휴양림 37.14806356 128.045293
203 옥전자연휴양림 37.174689 128.089444
204 충북알프스자연휴양림 36.57319259 127.7858718
205 속리산숲체험휴양마을 36.49245548 127.7924743
206 장령산자연휴양림 36.24486737 127.5547497
207 민주지산자연휴양림 36.05313182 127.8243888
208 좌구산자연휴양림 36.70556821 127.6511216
209 횡성자연휴양림 37.53904383 128.1118525
210 주천강자연휴양림 37.4606019 128.2034233
211 숲체원 37.53722046 128.2866886
212 청태산휴양림 37.52907993 128.2968658

In [54]:
for n, row in df.iterrows():
    mk = folium.Marker(location=[row["위도"], row["경도"]],
                       popup=folium.Popup(row["휴양림명"], max_width=200))
    mk.add_to(anMap)
anMap

In [55]:
anMap2 = folium.Map(location=[37.4965, 126.9573],
                    zoom_start=10,
                    zoom_control=False,
                    control_scale=True)
anMap2

In [58]:
from folium.plugins import MarkerCluster
mc = MarkerCluster().add_to(anMap2)

for _, row in df.iterrows():
    folium.Marker(location=[row["위도"], row["경도"]],
                  popup=folium.Popup(row["휴양림명"], max_width=200)
                 ).add_to(mc)

anMap2